### ISSUE TITLE
Jstohtml is giving hexa decimal characters if href is having '/' . I have seen the code of this in index.js the '/' and few other special characters are replaced with hexa code. So we need slashes only instead of hexa code. I think there is no way to get that done after passing object to jstohtml

### ISSUE THREAD

**Issue by keerthi567** [hcodes/jstohtml#11]
Jstohtml is giving hexa decimal characters if href is having '/' . I have seen the code of this in index.js the '/' and few other special characters are replaced with hexa code. So we need slashes only instead of hexa code. I think there is no way to get that done after passing object to jstohtml

**Comment by hcodes** [comment]
Thank you, this is a bug.

**Comment by hcodes** [comment]
v2.2.0
